name: RabInteractive

channels:
  - defaults
  - bioconda
  - conda-forge

dependencies:
  - biopython=1.83
  - goatools=1.2.3
  - jupyterlab=3.3.2
  - matplotlib=3.8.4
  - natsort=7.1.1
  - numpy=1.26.4
  - openpyxl=3.1.0
  - pandas=2.1.4
  - pybiomart=0.2.0
  - python=3.10.14
  - scipy=1.13.1
  - pip=23.3.2
  - pip:
    - upsetplot==0.9.0
    - matplotlib-venn==1.1.2

